version: "3"
services:
  mysql:
    image: mysql:5.7.6
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: 
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 
